plugins:
  - rubocop-katalyst

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    # Dummy app
    - spec/dummy/tmp/**/*
    - spec/dummy/node_modules/**/*
    - spec/dummy/vendor/bundle/**/*
