require:
  - rubocop-capybara
  - rubocop-katalyst
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
