name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.7.8
          - 3.2.2

    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn install
      - name: Run setup
        run: |
          bin/setup
      - name: Run default rake task
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake
